sudo: required
services:
  - docker

before_install:
  - docker build -t nerdylegend/frontend -f Dockerfile.dev .

script:
  - docker run nerdylegend/frontend npm test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-2-268161157189"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
